**Downloading, Installing & Importing Required Libraries**

In [20]:
import pandas as pd

**Mounting Google Drive for importing the Data Files which will be used in the Tokenization**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

**Defining Post Processing Methods**

**Method to Remove the unnecessary Spaces occuring in the instructions of the Novel Recipe**

In [ ]:
def removeSpacesFromRecipeInstructions(df):
  recipeIns=list(df['Recipe Instructions'])
  finalIns=list()
  for eachIns in recipeIns:
    x=eachIns.strip()
    finalIns.append(x)
  df=df.drop(['Recipe Instructions'], axis=1)
  df['Recipe Instructions']=finalIns
  return df

**Method to Remove the unnecessary column occuring the csv File named "Unnamed: 0"**

In [ ]:
def removeUnnamed0Column(df):
  df=df.drop(['Unnamed: 0'], axis=1)
  return df

**Method to Remove the unnecessary column occuring the csv File named "Unnamed: 0.1"**

In [ ]:
def removeUnnamed01Column(df):
  df=df.drop(['Unnamed: 0.1'], axis=1)
  return df

**Method to Rename the columns of Final Dataframe which will contain Post Processed Novel Recipes**

In [ ]:
def renameColumns(df):
  df.rename(columns = {'Recipe Titile':'title'}, inplace = True)
  df.rename(columns = {'Ingredient Phrases':'ingredients'}, inplace = True)
  df.rename(columns = {'Recipe Instructions':'instructions'}, inplace = True)
  return df

**Method to Assign Recipes IDs to each Novel Recipe, startId parameter of this method will store the starting ID from which you want to start assigning. By default, loop in this method runs for 10k iterations, means it will assign Ids from startId to next 10k recipes, change it according to your need.**

In [ ]:
def assignRecipeIds(df,startId):
  recipesIds=[]
  for i in range(startId,startId+10000):
    currentRecipeId=str(i+1)
    recipesIds.append(currentRecipeId)
  df['Sno']=recipesIds
  df.set_index('Sno',inplace=True)
  return df

**Method to Remove the "Random Ingredients" column**

In [ ]:
def removeRandomIngredientColumn(df):
  df=df.drop(['Random Ingredients'], axis=1)
  return df

**Steps of Splitting of CSV File Data into multiple parts**

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_13.csv')

In [ ]:
df.shape

(3500, 5)

In [ ]:
partOne=df.iloc[0:500,:]
partTwo=df.iloc[500:2500,:]
partThree=df.iloc[2500:,:]

In [ ]:
partOne.shape

(500, 5)

In [ ]:
partTwo.shape

(2000, 5)

In [ ]:
partThree.shape

(1000, 5)

In [ ]:
partOne.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/500_Niharika_13.1.csv')

In [ ]:
partTwo.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/2000_Niharika_13.2.csv')

In [ ]:
partThree.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/1000_Niharika_13.3.csv')

**Generation of Batches of Novel Recipes Start from here:**

**The 1st and 2nd batch are post Processed manually by the developing team, We have developed and used this notebook for post processing for all the remaining batches.**

**Prepairing 3rd batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Adarsh Results/Adarsh_5_1000_Recipes.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Adarsh Results/Adarsh_8_4000_Recipes.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_2_1500.csv')
df4=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_3_3500.csv')

In [ ]:
df=pd.concat([df1,df2,df3,df4])

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,0,0.0,"green olive,bread,cranberry sauce,chile pepper...",Spicy Chilli and Tomato Soup,8 slices bread | 1/3 cup red curry paste | 2 ...,Preheat the oven to 350 degrees f. Brush a 9x...
1,1,1.0,"rosemary,red chili,saffron",Advieh - Persian Saffron Roast Spice Blend,"5 tablespoons saffron, soaked in | 1/2 teaspo...",Grind or pound saffron into a powder with 1/2...
2,2,2.0,"venison roast,parmesan cheese,kielbasa,potato",Irish Pot Roast,2 large potatoes | 3 lbs smoked baby back rib...,Cover whole pot with water and bring to boil ...
3,3,3.0,"parsley sprig,seasoning salt,plain nonfat yogu...",Curried Rotini Pasta,"1 1/2 cups rotini pasta, dry and broken into ...","In large bowl, toss drained pasta with yogurt..."
4,4,4.0,"confectioner sugar,spaghetti,tomato paste,brus...",Quick and Easy Chicken N' N' Pasta,1 pound uncooked smoked chicken breast halves...,"Combine the chicken, tomato paste, and confec..."

In [ ]:
df=removeUnnamed0Column(df)

In [ ]:
df=removeUnnamed01Column(df)

In [ ]:
df.head()

,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,"dark turkey meat,tortilla,moroccan seasoning,c...",Moroccan Style Beef Wraps (21 Day Wonder Diet:...,600 g dark turkey meat | 1 1/2 teaspoons curr...,Cook turkey over medium heat in a medium sauc...
1,"golden raisin,pepperjack cheese,ginger garlic ...",Crock Pot Welsh Rarebit,6 -8 ounces boneless blade steak | 1/4 cup fr...,Put the first 3 ingredients in the crockpot. ...
2,"italian sausage,beef brisket,tomato juice",Easy Brisket,"2 large italian sausage, or other ground beef...",Preheat oven to 300 degrees f. Place brisket ...
3,"coriander powder,garam masala,cardamom",Garam Masala Spice Blend,1 1/2 teaspoons coriander powder | 1/2 teaspo...,Using an electric spice mill grind coriander ...
4,"onion soup mix,beef,bell pepper,cheese tortell...",Quick Cheez Chili Beef Pasta,"1 lb beef | 12 ounces cheese tortellini, unco...",Cut beef into 1 thick slices. Place slices be...

In [ ]:
df=removeSpacesFromRecipeInstructions(df)

In [ ]:
df=assignRecipeIds(df,20000)

In [ ]:
df.head()

,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
Sno,,,,
20001,"dark turkey meat,tortilla,moroccan seasoning,c...",Moroccan Style Beef Wraps (21 Day Wonder Diet:...,600 g dark turkey meat | 1 1/2 teaspoons curr...,Cook turkey over medium heat in a medium sauce...
20002,"golden raisin,pepperjack cheese,ginger garlic ...",Crock Pot Welsh Rarebit,6 -8 ounces boneless blade steak | 1/4 cup fr...,Put the first 3 ingredients in the crockpot. T...
20003,"italian sausage,beef brisket,tomato juice",Easy Brisket,"2 large italian sausage, or other ground beef...",Preheat oven to 300 degrees f. Place brisket i...
20004,"coriander powder,garam masala,cardamom",Garam Masala Spice Blend,1 1/2 teaspoons coriander powder | 1/2 teaspo...,Using an electric spice mill grind coriander p...
20005,"onion soup mix,beef,bell pepper,cheese tortell...",Quick Cheez Chili Beef Pasta,"1 lb beef | 12 ounces cheese tortellini, unco...",Cut beef into 1 thick slices. Place slices bet...

In [ ]:
df=renameColumns(df)

In [ ]:
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients3.csv')

In [ ]:
df=removeRandomIngredientColumn(df)

In [ ]:
df.head()

,title,ingredients,instructions
Sno,,,
20001,Moroccan Style Beef Wraps (21 Day Wonder Diet:...,600 g dark turkey meat | 1 1/2 teaspoons curr...,Cook turkey over medium heat in a medium sauce...
20002,Crock Pot Welsh Rarebit,6 -8 ounces boneless blade steak | 1/4 cup fr...,Put the first 3 ingredients in the crockpot. T...
20003,Easy Brisket,"2 large italian sausage, or other ground beef...",Preheat oven to 300 degrees f. Place brisket i...
20004,Garam Masala Spice Blend,1 1/2 teaspoons coriander powder | 1/2 teaspo...,Using an electric spice mill grind coriander p...
20005,Quick Cheez Chili Beef Pasta,"1 lb beef | 12 ounces cheese tortellini, unco...",Cut beef into 1 thick slices. Place slices bet...

In [ ]:
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients3.csv')

**Prepairing 4th batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Adarsh Results/Adarsh_9_5000_Recipes.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Adarsh Results/Adarsh_10_5000_Recipes.csv')

In [ ]:
df=pd.concat([df1,df2])

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,0,"cream mushroom soup,white miso",Miso Cream Sauce for Seafood,8 ounces light cream of mushroom soup | 1 oun...,Put 1 oz of cream of mushroom soup into small...
1,1,"asparagus,white pepper,ranch salad dressing,ra...",Asparagus Salad (Ranch Asparagus),1 cup chopped fresh asparagus | 1/2 cup thinl...,"Toss the asparagus, purple onion, 1 tablespoo..."
2,2,"parsnip,bok choy,fennel seed",Bok Choy - Parsnip and Fennel Chowder,1 bunch parsnip | 1 teaspoon fennel seed | 1 ...,Rinse and peel potatoes and cut into 1/2 inch...
3,3,"serrano chilies,baking soda,liquid smoke,cauli...",Smoky Cauliflower,1 head cauliflower | 2 serrano chilies | 2 cu...,Steam the cauliflower until the leaves are se...
4,4,"chili garlic sauce,white flour,hoisin sauce,ca...",Quick Hot Dog,"1 lb good quality beef round steak, thinly sl...","Mix hoisin sauce, flour, tomatoes, green chil..."

In [ ]:
df=removeUnnamed0Column(df)

In [ ]:
df.head()

,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,"cream mushroom soup,white miso",Miso Cream Sauce for Seafood,8 ounces light cream of mushroom soup | 1 oun...,Put 1 oz of cream of mushroom soup into small...
1,"asparagus,white pepper,ranch salad dressing,ra...",Asparagus Salad (Ranch Asparagus),1 cup chopped fresh asparagus | 1/2 cup thinl...,"Toss the asparagus, purple onion, 1 tablespoo..."
2,"parsnip,bok choy,fennel seed",Bok Choy - Parsnip and Fennel Chowder,1 bunch parsnip | 1 teaspoon fennel seed | 1 ...,Rinse and peel potatoes and cut into 1/2 inch...
3,"serrano chilies,baking soda,liquid smoke,cauli...",Smoky Cauliflower,1 head cauliflower | 2 serrano chilies | 2 cu...,Steam the cauliflower until the leaves are se...
4,"chili garlic sauce,white flour,hoisin sauce,ca...",Quick Hot Dog,"1 lb good quality beef round steak, thinly sl...","Mix hoisin sauce, flour, tomatoes, green chil..."

In [ ]:
df=removeSpacesFromRecipeInstructions(df)

In [ ]:
df=assignRecipeIds(df,30000)

In [ ]:
df.head()

,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
Sno,,,,
30001,"cream mushroom soup,white miso",Miso Cream Sauce for Seafood,8 ounces light cream of mushroom soup | 1 oun...,Put 1 oz of cream of mushroom soup into small ...
30002,"asparagus,white pepper,ranch salad dressing,ra...",Asparagus Salad (Ranch Asparagus),1 cup chopped fresh asparagus | 1/2 cup thinl...,"Toss the asparagus, purple onion, 1 tablespoon..."
30003,"parsnip,bok choy,fennel seed",Bok Choy - Parsnip and Fennel Chowder,1 bunch parsnip | 1 teaspoon fennel seed | 1 ...,Rinse and peel potatoes and cut into 1/2 inch ...
30004,"serrano chilies,baking soda,liquid smoke,cauli...",Smoky Cauliflower,1 head cauliflower | 2 serrano chilies | 2 cu...,Steam the cauliflower until the leaves are sep...
30005,"chili garlic sauce,white flour,hoisin sauce,ca...",Quick Hot Dog,"1 lb good quality beef round steak, thinly sl...","Mix hoisin sauce, flour, tomatoes, green chile..."

In [ ]:
df=renameColumns(df)

In [ ]:
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients4.csv')

In [ ]:
df=removeRandomIngredientColumn(df)

In [ ]:
df.head()

,title,ingredients,instructions
Sno,,,
30001,Miso Cream Sauce for Seafood,8 ounces light cream of mushroom soup | 1 oun...,Put 1 oz of cream of mushroom soup into small ...
30002,Asparagus Salad (Ranch Asparagus),1 cup chopped fresh asparagus | 1/2 cup thinl...,"Toss the asparagus, purple onion, 1 tablespoon..."
30003,Bok Choy - Parsnip and Fennel Chowder,1 bunch parsnip | 1 teaspoon fennel seed | 1 ...,Rinse and peel potatoes and cut into 1/2 inch ...
30004,Smoky Cauliflower,1 head cauliflower | 2 serrano chilies | 2 cu...,Steam the cauliflower until the leaves are sep...
30005,Quick Hot Dog,"1 lb good quality beef round steak, thinly sl...","Mix hoisin sauce, flour, tomatoes, green chile..."

In [ ]:
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients4.csv')

**Prepairing 5th batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_6.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_7.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_6_3000_Recipes.csv')

In [ ]:
df=pd.concat([df1,df2,df3])

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions,Unnamed: 0.1
0,0,"kalamata olive,onion soup mix,romaine lettuce ...",Korean Beef and Shiitake Lettuce Wraps,1 cup plain yogurt | 1/4 cup grated miniature...,"In a bowl, stir together the yogurt, chocolat...",NaN
1,1,"wasabi paste,ancho chile powder,ginger,seasoni...",Wasabi-Glazed Fried Potatoes,"3 russet potatoes, quartered | 1 tablespoon s...",Preheat oven to 400 degrees f. Lightly grease...,NaN
2,2,"chili paste,mace,mexican cheese,apple juice,wh...","Applejack ""Pierce"" Beef Sandwiches",2 lbs rump roast or 2 lbs top round beef | 2 ...,Cover roast with water.\n\n\n,NaN
3,3,"coconut milk,green chilies",Green Chilies in Coconut Milk,15 1/2 ounces coconut milk | 1 3/4 ounces gre...,"Combine all ingredients in a pot, and simmer ...",NaN
4,4,"chicken wing,scallion,seasoning salt,guacamole...",Quick Tex Mex Chili Wings With Spicy Goya...,"1 1/2 lbs chicken wings | 1 can chickpeas, wi...",Rinse and drain the chicken wings. Remove all...,NaN

In [ ]:
df=removeUnnamed0Column(df)
df=removeUnnamed01Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,40000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients5.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients5.csv')

**Prepairing 6th batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_7_3000_Recipes.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/3500_Parul_9.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_9.csv')

In [ ]:
df=pd.concat([df1,df2,df3])

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,0,0.0,"sushi rice,stew meat,hard egg,currant,basil,gr...",Korean Beef and Egg Roll,36 ladyfingers | 1 lb sirloin stew meat or 1 ...,"Make the sticky rice, in a large skillet set ..."
1,1,1.0,"sesame seed,almond paste",Sesame Paste... or Spread,6 -8 tablespoons almond paste | 1 tablespoon ...,"Mix, store in airtight container or in the re..."
2,2,2.0,"date,oil",Kuwaiti Date Balls,50 dates | 3 tablespoons oil | 500 ml oil,"Put dates in a blender, add oil, stir, grind ..."
3,3,3.0,"lasagna noodle,caper,chili oil,sharp cheddar c...",Cheese and Chili Oil Lasagna,32 ounces rotelle pasta | 1/2 lb sharp chedda...,"Cook pasta in boiling water. Meanwhile, in a ..."
4,4,4.0,"granny smith apple,white pearl onion,white flo...",Quick Italian White Applesauce,5 large italian-style peeled white pearl onio...,Place the pearl onions into a medium saucepan...

In [ ]:
df.shape

(10000, 6)

In [ ]:
df=removeUnnamed0Column(df)
df=removeUnnamed01Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,50000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients6.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients6.csv')

**Prepairing 7th batch of 10000 recipes**

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Adarsh Results/Adarsh_11_10000_Recipes.csv')

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,0,"chili pepper,chicken breast half,garlic paste",Korma,1 tablespoon garlic paste | 4 boneless chicke...,Cook 1 tablespoon garlic paste in a non stick...
1,1,"poultry seasoning,seashell pasta,chicken bouil...",Crock Pot Easiest Broth,2 bags seashell pasta | 1 chicken bouillon cu...,Pour in the chicken bouillon cube. Place und...
2,2,"curry powder,ladyfinger,penne pasta,chocolate,...",Caramelized Grilled Pasta Salad,3 ounces uncooked penne pasta | 2 1/4 cups bu...,Cook pasta as directed on package. Reserve 1...
3,3,"milk,garlic clove",Brazilian Garlic Soup,"4 garlic cloves, minced | 1 can sweetened con...",Mince the garlic and combine it with the cond...
4,4,"ginger garlic paste,heavy cream,red chilies,ga...",The Ultimate White Sauce for Vegetables,"2 1/2 ounces fresh red chilies, chopped | 3/4...",Combine all the ingredients in a food process...

In [ ]:
df.shape

(10000, 5)

In [ ]:
df=removeUnnamed0Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,60000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients7.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients7.csv')

**Prepairing 8th batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/1500_Niharika_8.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_10.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_8.1_2000_Recipes.csv')
df4=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_10.1_3000_Recipes.csv')

In [ ]:
df=pd.concat([df1,df2,df3,df4])

In [ ]:
df.shape

(10000, 6)

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions,Unnamed: 0.1
0,0,"chocolate square,cumin,white tuna",Tuna and Chocolate Balls - Spain,"1/2 cup white tuna, cooked and drained | 2 un...","In a large bowl, stir together tuna, chocolat...",NaN
1,1,"pepperoni,breadcrumb,beer",Coney-Pimiento Beer Bread,8 ounces breadcrumbs | 1/4 lb pepperoni | 14 ...,"In a large bowl, combine bread crumbs and pep...",NaN
2,2,"phyllo dough,garlic powder,catsup,red pepper f...",Bacon Wrapped Eggplant (Russian Pepperoncini),"1 large eggplant, diced small | 1 can french ...",Cook eggplant until tender on the outside and...,NaN
3,3,"green bean,marmalade,romaine lettuce",Green Beans and Marmalade Salad,1 pound fresh green beans | 1/2 cup marmalade...,Cut ends off each green bean and snap the end...,NaN
4,4,"cream chicken soup,chipotle chile,tap water",Quick Mexican Cream Soup,1 can cream of chicken soup ( campbell's bran...,Combine all ingredients until smooth. Serve w...,NaN

In [ ]:
df=removeUnnamed0Column(df)
df=removeUnnamed01Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,70000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients8.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients8.csv')

**Prepairing 9th batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_11.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_12.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_11.1_3000_Recipes.csv')

In [ ]:
df=pd.concat([df1,df2,df3])

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions,Unnamed: 0.1
0,0,"palm sugar,chocolate,wasabi,cider vinegar",Wasabi Chaat,1 cup good quality chocolate ( bittersweet is...,The measurements are approximate and the prop...,NaN
1,1,"turmeric powder,anaheim chili,tomato sauce,bak...","Crock Pot Chili (Cooking, Microwave & Low Fat)","2 medium baking potatoes, scrubbed | 2 cans t...",Spray crock pot with non stick spray. In smal...,NaN
2,2,"peach,rigatoni pasta,hazelnut,cremini mushroom...",Apple and Hazelnut Rigatoni Salad,3/4 cup smooth peanut butter | 2/3 cup packed...,"In a small bowl, cream together peanut butter...",NaN
3,3,"almond extract,bacon",Almond Crisps,1/2 lb bacon | 1/2 teaspoon almond extract,Preheat oven to 375 degrees f. Line a cookie ...,NaN
4,4,"grand marnier,salmon,creamy goat cheese,tamari...",Quick Greek Salmon With Whole Grain Cream,"1 lb fresh salmon ( skinned, bones removed, s...",Mix yogurt and cream cheese in a large bowl t...,NaN

In [ ]:
df=removeUnnamed0Column(df)
df=removeUnnamed01Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,80000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients9.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients9.csv')

**Prepairing 10th batch of 10000 recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/3500_Parul_12.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/3500_Parul_13.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_10.2_500_Recipes.csv')
df4=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_11.2_500_Recipes.csv')
df5=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/Parul_8.2_1000_Recipes.csv')
df6=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/1000_Niharika_13.3.csv')

In [ ]:
df=pd.concat([df1,df2,df3,df4,df5,df6])

In [ ]:
df.shape

(10000, 6)

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions,Unnamed: 0.1
0,0,"macaroni,breadcrumb,maple syrup,double cream,o...",Curry Mac and Beef With Pastrami,200 g macaroni | 1 teaspoon cornstarch | 100 ...,Boil water and add the macaroni. Remove shell...,NaN
1,1,"vegetable,salsa,cashew",Creamy Cashew Dip,6 -8 cups of chopped assorted raw nuts | 24 o...,"In large bowl, mix all ingredients in microwa...",NaN
2,2,"escarole,red bell pepper,chicken leg,salt seas...",Baking Green Beans & Chicken,2 packages dried escarole | 1 head green chil...,Soak escarole in large pot of water 2 hours u...,NaN
3,3,"grain rice,lemon zest",Lemon Rice Pilaf,"1 cup light or regular long-grain rice, washe...","Place rice in a bowl, season with salt to tas...",NaN
4,4,"escarole,black mustard seed,dark corn syrup,mo...",Clams & Broccoli,3 lbs escarole ( fresh or frozen ) | 1 head b...,Combine all ingredients in medium size saucep...,NaN

In [ ]:
df=removeUnnamed0Column(df)
df=removeUnnamed01Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,90000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithRandomIngredients10.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10000RecipesWithoutRandomIngredients10.csv')

**Prepairing 11th batch containing 9.5k recipes**

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/2000_Niharika_13.2.csv')
df2=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/3500_Niharika_14.csv')
df3=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Niharika Results/500_Niharika_13.1.csv')
df4=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Parul Results/3500_Parul_14.csv')

In [ ]:
df=pd.concat([df1,df2,df3,df4])

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,500,500.0,"chili pepper flake,green,bay leaf,pork fillet,...",Korean Beef Pie,2 tablespoons black pickled chili pepper flak...,"In a shallow dish, whisk 1/2 cup water with t..."
1,501,501.0,"caper,parsley,sauerkraut,orange peel,margarine...",Gourmet Sauerkraut Filling,"12 slices mini hamburger buns, cut in half | ...",Melt margarine in large skillet. Add drained ...
2,502,502.0,"seasoning mix,stilton cheese",Stilton Cheese Spread,1 package stilton cheese | 1 package seasonin...,Cut Stilton into cubes. Blend mixture and sto...
3,503,503.0,"salsa,tarragon vinegar,macadamia nut,chicken m...",Brazilian Haystacks (Macadamia Nut and Bacon),2 tablespoons chocopher chips | 2 tablespoons...,Place the chocadamias on a plate and place on...
4,504,504.0,"tortilla,barbecue sauce",Way Too Easy Burritos,"3/4 cup barbecue sauce, your favourite flavor...",Spread your favourite bbq sauce on both sides...

In [ ]:
df.shape

(9500, 6)

In [ ]:
df=removeUnnamed0Column(df)
df=removeUnnamed01Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,100000)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/9500RecipesWithRandomIngredientsBatch11.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/9500RecipesWithoutRandomIngredientsBatch11.csv')

In [ ]:
df.tail()

,title,ingredients,instructions
Sno,,,
109496,Quick Philly Cheesesteak,1 pound ground beef bouillon | 6 ounces dried...,Heat a large skillet over medium heat. Cook an...
109497,Tortilla & Chickpea Salad,"12 tortillas ( fresh, frozen or previously re...","Tortillas, preheat a grill pan to medium. Tear..."
109498,Pesto Swiss Rolled-up Pork Tenderloin,4 slices lean pork tenderloin | 2/3 cup nonfa...,Mix pesto with grated cheese and orange blosso...
109499,Mashed Potato Balls II,"2 pounds red potatoes, cubed | 3 hard-cooked ...",Place potatoes into a saucepan with enough wat...
109500,Beef and Rotini Tostadas #RSC,1 lb rib eye steak | 1 cup sliced spanish oni...,Preheat oven to 500°f. Cut steak into thin str...

**Prepairing 12th(Final) batch containing 10.5k recipes**

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Adarsh Results/Adarsh_12_10500_Recipes.csv')

In [ ]:
df.head()

,Unnamed: 0,Random Ingredients,Recipe Titile,Ingredient Phrases,Recipe Instructions
0,0,"white sugar,chicken breast,cinnamon raisin bre...",Kathleen's Wild Rice Chicken,8 chicken breasts | 1 loaf cinnamon raisin br...,Preheat the oven to 350 degrees f. Arrange t...
1,1,"stock,rye bread,oyster sauce,cucumber",Cucumber and Corned Rye,2 cucumbers | 300 ml stock | 2 tablespoons oy...,"Cut the rye bread in half, hollow out if nece..."
2,2,"fennel seed,fennel bulb,chili garlic sauce,oni...",Quick and Easy Parsnips and Chips,3 parsnips | 1 tablespoon fennel seed | 1 tea...,Preheat oven to 400 degrees f. Line a baking...
3,3,"lasagna noodle,orange zest,amarula cream lique...",Amarula Cream Pastries,15 sheets frozen phyllo pastry | 1 3/4 cups a...,Remove any loose sheets of phyllo pastry. Us...
4,4,"red wine vinegar,cashew,wesson oil,red curry p...",Quick Gnocchi Salad,"1 lb uncooked rotisserie-cooked chicken, torn...",Toss chicken with seasonings in a large bowl....

In [ ]:
df.shape

(10500, 5)

In [ ]:
df=removeUnnamed0Column(df)
df=removeSpacesFromRecipeInstructions(df)
df=assignRecipeIds(df,109500)
df=renameColumns(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10500RecipesWithRandomIngredientsBatch12.csv')
df=removeRandomIngredientColumn(df)
df.to_csv('/content/drive/MyDrive/Monsoon22_conditional_recipe_gen/Recipe Result/Merged Recipes/10500RecipesWithoutRandomIngredientsBatch12.csv')

In [ ]:
df.tail()

,title,ingredients,instructions
Sno,,,
119996,"Ham, Pineapple and Green Onion Salad","3/4 pound fresh ham, cut into matchsticks ( o...",Place ham in a medium skillet. Pour pineapple...
119997,Pan Seared Beef Tenderloin,"1 1/2 lbs beef tenderloin, 1 cut into 12 equa...",Preheat grill to medium heat and lightly oil a...
119998,Jalepeno Peppers and Chocolate (Jalapeno Nibbles),2 large jalapeno peppers | salt & freshly gro...,"Wash, slit, and deseed the peppers. You can a..."
119999,Southern Style Chicken,"4 skinless, boneless chicken breast halves | ...",Season the chicken breasts with the seasoning ...
120000,Apricot-Glazed Bean Sandwich,"1 can cannellini beans, rinsed and drained | ...",Preheat oven to 325 degrees f. Combine the be...

**Therefore, Total We have delivered 120k Novel Recipes ✅**